plugins {
    id "com.github.johnrengelman.shadow"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

loom {
    accessWidenerPath = project(":common").file("src/main/resources/ldlib2.accesswidener")
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    modImplementation "dev.architectury:architectury-fabric:${rootProject.architectury_api_version}"

    implementation("org.jetbrains.kotlin:kotlin-stdlib:${rootProject.kotlin_stdlib_version}") {
        exclude group: "org.jetbrains", module: "annotations"
    }
    include("org.jetbrains.kotlin:kotlin-stdlib:${rootProject.kotlin_stdlib_version}") {
        transitive = false
    }
    implementation "org.appliedenergistics.yoga:yoga:${rootProject.yoga_version}"
    implementation("dev.vfyjxf:taffy:${rootProject.taffy_version}") {
        exclude group: "it.unimi.dsi", module: "fastutil"
    }
    modImplementation "io.github.llamalad7:mixinextras-fabric:0.5.4"
    include "io.github.llamalad7:mixinextras-fabric:0.5.4"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowBundle project(path: ":common", configuration: "transformProductionFabric")
    shadowBundle "org.appliedenergistics.yoga:yoga:${rootProject.yoga_version}"
    shadowBundle("dev.vfyjxf:taffy:${rootProject.taffy_version}") {
        exclude group: "it.unimi.dsi", module: "fastutil"
    }

    developmentFabric("org.jetbrains.kotlin:kotlin-stdlib:${rootProject.kotlin_stdlib_version}") {
        exclude group: "org.jetbrains", module: "annotations"
    }
    developmentFabric "org.appliedenergistics.yoga:yoga:${rootProject.yoga_version}"
    developmentFabric("dev.vfyjxf:taffy:${rootProject.taffy_version}") {
        exclude group: "it.unimi.dsi", module: "fastutil"
    }
    developmentFabric "io.github.llamalad7:mixinextras-fabric:0.5.4"
}

processResources {
    inputs.properties([
            version: project.version,
            mod_id: rootProject.mod_id,
            mod_name: rootProject.mod_name,
            mod_description: rootProject.mod_description,
            mod_license: rootProject.mod_license,
            mod_url: rootProject.mod_url,
            minecraft_version: rootProject.minecraft_version,
            fabric_loader_version: rootProject.fabric_loader_version,
            architectury_api_version: rootProject.architectury_api_version
    ])
    filesMatching("fabric.mod.json") {
        expand(inputs.properties)
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "dev-shadow"
    exclude "javax/annotation/**"
    exclude "edu/umd/cs/findbugs/**"
    exclude "org/jetbrains/annotations/**"
    exclude "module-info.class"
    exclude "META-INF/versions/**"
}

remapJar {
    input.set shadowJar.archiveFile
}
